
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stichub-server
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: nareshchandanbatve/stichhub:server
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
             name: my-secret
        ports:
        - containerPort: 5000
