
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stichub-client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: nareshchandanbatve/stichhub:client
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 5173
